---
title: "bootstrap"
author: "Weijia Xiong"
date: "11/14/2019"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(p8105.datasets)
library(modelr)
library(mgcv)
set.seed(1)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

```



```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = sim_df_const %>% 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

```{r}
sim_df = 
  bind_rows(const = sim_df_const, nonconst = sim_df_nonconst, .id = "data_source") 

sim_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  facet_grid(~data_source) 
```


```{r}
sim_df_const %>% 
  lm(y ~ x, data = . ) %>% 
  broom::tidy() 

sim_df_nonconst %>% 
  lm(y ~ x, data = . ) %>% 
  broom::tidy() 
```

## how can i bootstrap 

write a function to draw a bootsrap sample based on a dataframe
```{r}
sim_df_nonconst %>% 
  sample_frac(size = 1 ,replace = TRUE) %>%  ## take the sample with replacement(some x appear more than once), size: proportion, 1: 100%
  arrange(x)


boot_sample = function(df) {
  sample_frac(df, size = 1 ,replace = TRUE)
}
```


```{r}
boot_sample(sim_df_nonconst) %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm")
```
some original data points appear more than once, others don’t appear at all.



Organize a dataframe
rerun bootsample
```{r}
boot_straps = 
  tibble(
    strap_num = 1:1000,
    strap_sample = rerun(1000,boot_sample(df = sim_df_nonconst))
  )
```

```{r}
boot_straps %>% 
  filter(strap_num %in% 1:2) %>% 
  mutate(strap_sample = map(strap_sample, ~arrange(.x, x))) %>% 
  pull(strap_sample)
```


```{r}
boot_straps %>% 
  filter(strap_num %in% 1:3) %>% 
  unnest(strap_sample) %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm", se = FALSE) +
  facet_grid(~strap_num) 
```

Do some kind of analysis...

```{r}
bootstrap_results =
  boot_straps %>% 
  mutate(
    models = map(strap_sample,~ lm(y ~ x, data = .x)),
    results = map(models,broom::tidy)
  ) %>% 
  select(-strap_sample,-models) %>% 
  unnest(results)
```

summarize these results

```{r}
bootstrap_results %>% 
  group_by(term) %>% 
  summarise(
    se = sd(estimate)
  )
```
se is too low!

use package

```{r}
sim_df_nonconst %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(
    models = map(strap,~ lm(y ~ x, data = .x)),
    results = map(models,broom::tidy)
  ) %>% 
  select(-strap,-models) %>% 
  unnest(results)


boot_straps$strap[[1]]
## <resample [250 x 3]> 8, 132, 69, 225, 180, 122, 34, 170, 216, 122, ...
as_data_frame(boot_straps$strap[[1]])
```



```{r}

sim_df_nonconst %>% 
  lm(y ~ x, data = . ) %>% 
  broom::tidy() 

sim_df_nonconst %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(
    models = map(strap,~lm(y ~ x, data = .x)),
    results = map(models,broom::tidy)
  ) %>% 
  select(-strap,-models) %>% 
  unnest(results) %>% 
  group_by(term) %>% 
  summarise(boot_se = sd(estimate))

```



check for const
```{r}

sim_df_const %>% 
  lm(y ~ x, data = . ) %>% 
  broom::tidy() 


sim_df_const %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(models = map(strap, ~lm(y ~ x, data = .x) ),
         results = map(models, broom::tidy)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  group_by(term) %>% 
  summarize(boot_se = sd(estimate))
```


## Airbnb
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)

```


```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = room_type)) + 
  geom_point() 
```


```{r}
airbnb_results = 
 nyc_airbnb %>% 
  filter(boro == "Manhattan") %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(
    models = map(strap, ~ lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(results) %>% 
  unnest(results)

```

Make a plot of the `stars`
```{r}
airbnb_results %>% 
  filter(term == "stars") %>% 
  ggplot(aes(x = estimate)) + geom_density()
```

Skew!


